# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "PaperWorks"
license = "MIT"
licenselink = "https://github.com/dridani/PaperWorks/blob/master/LICENSE"
description = "A fast and Minimalist Hugo theme"
homepage = "https://paperworks.pages.dev/"
demosite = "https://paperworks.pages.dev/"
tags = [
  "responsive",
  "simple",
  "clean",
  "light",
  "dark",
  "blog",
  "minimalist",
  "highlight.js",
  "search",
]
features = [
  "responsive",
  "single-column",
  "blog",
  "cover-image",
  "table-of-contents",
  "opengraph",
  "highlight.js",
  "favicon",
  "archive",
  "share-icons",
  "cover",
  "multilingual",
  "social-icons",
  "minified-assets",
  "theme-toggle",
  "menu-location-indicator",
  "scroll-to-top",
  "search",
]
min_version = "0.146.0"

[author]
name = "dridani"
homepage = "https://github.com/dridani/"

# If porting an existing theme
[original]
name = "PaperMod"
author = "Aditya Telange"
homepage = "https://github.com/adityatelange"
repo = "https://github.com/adityatelange/hugo-PaperMod/"
